from abc import ABC, abstractmethod

class LLMInterface(ABC):
    """
    A base class for Large Language Model interfaces.
    This class defines the methods that must be implemented
    to interact with any LLM.
    """
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        """
        Generate a response from the LLM given the prompt.

        :param prompt: The input prompt for the LLM.
        :return: A string response generated by the LLM.
        """
        pass